### PR TITLE
Added moving selection [WIP]

### PR DESCRIPTION
**Pull request by TheThirdOne**
PR for #290

There are two main problems before this can be merged in:
1. The selection currently does not stay visible after changing to another tool.
2. Pressing escape doesn't remove the selection.

### CODE REVIEW

**Comment by juliandescottes** [comment]
Thanks ! Looks like a good start.

Some comments on top of what you mentioned : 

1. When a selection is active, the move tool should always move the selection, regardless of where you clicked for the move. If there is no selection, the move tool should move the whole frame. (simply )

2. When using the moveTool with a selection, the selection should also be moved.

3. The selection is not persisted during when saving a move state. I think the easiest is to backup the pixels of the selection when saving the move state and use this information when replaying the state. Since the move tool is the only tool impacted by the selection for now I think this should be fine.

What do you think ?

**Comment by TheThirdOne** [comment]
1. I can make that happen as soon as dismissing selection works.
2. Yup
3. That will probably be the last change I make.

**Comment by juliandescottes** [comment]
Sounds good, let me know if you need info/help on this !

**Comment by juliandescottes** [comment]
Linked issue closed, closing the PR

**Pull request closed without merging**
