### PR TITLE
Improve perfomance

### PR DESCRIPTION
**Pull request by david-szabo97**
# What's new?

- New format for .piskel files. It is saved as binary to save as many bytes as we can. (model version 3.0)
- Reworked the whole pixel storage, going from string to binary.
- Optimised rendering.
- Throttles to improve performance.
- Much faster loading of piskels.
- Much faster editing of piskels with high resolution and/or high count of frames/layers.
- FrameList controller now updates the DOM rather than recreating it every time

## TODO
- ~~Rewrite FramesList controller so it won't recreate the whole DOM every time~~

## Known Bugs
- ~~Can't create new frame when there is only 1 layer~~
- ~~Frames being deleted~~
- ~~Color swap and bucket tool not working properly~~

---
This change is [Reviewable](https://reviewable.io/reviews/juliandescottes/piskel/530)

### CODE REVIEW

**Comment by juliandescottes** [comment]
Thanks for the PR again :) there's definitely a performance improvement. 

Found some bugs so far, so I thought I'd report back. I'll do more testing tomorrow. 

The paint bucket seems to be broken. If you run the drawing tests (see https://github.com/juliandescottes/piskel/wiki/Test-Guidelines-:-Drawing-tests) it fails on the the bucket.drawing.json test. On a big sprite (512x512 for instance), the application is freezing when using repeatedly the paint bucket. Had to kill the browser.
I think the method paintSimilarConnectedPixelsFromFrame needs updating. 

The "color swap" tool no longer works on transparent pixels.

**Comment by david-szabo97** [comment]
Thank you, fixed it :smile:

**Comment by david-szabo97** [comment]
@juliandescottes 
Do you have any idea why these tests fail?
```
In test/casperjs/DrawingTest.js
  Untitled suite in test/casperjs/DrawingTest.js
    error: CasperError: Can't find module ./test/drawing/DrawingTests.casper.js
In test/casperjs/SmokeTest.js
  Untitled suite in test/casperjs/SmokeTest.js
    assertExists: Check if drawing canvas element is created
```

**Comment by juliandescottes** [comment]
How are you trying to run the tests ? Using grunt test-local or from a browser window ? From the error message, I guess it's coming from grunt? Maybe an incompatibe version of Casperjs installed

Try to run them from a browser window. You might need my fixes from https://github.com/juliandescottes/piskel/tree/fix-drawing-tests unless you are on Windows+Chrome

**Comment by david-szabo97** [comment]
It works fine if I run them in the browser, it fails with grunt. (Windows 10 + Chrome)
I have the latest CasperJS

**Comment by juliandescottes** [comment]
They are not compatible with the latest Casper (https://github.com/juliandescottes/piskel/issues/479).

**Comment by david-szabo97** [comment]
Pushed a commit which makes it compatible with latest CasperJS.
Dumped grunt-ghost and added grunt-casperjs. Ghost was kinda outdated.
Also added a polyfill for PhantomJS because Object.assign doesn't work in PhantomJS.

Drawing tests now working on Travis :smile: :yum:

**Comment by juliandescottes** [comment]
Amazing work! 

Interesting that just updating Casper makes the tests pass on Travis! I would have the thought the changes I made in https://github.com/juliandescottes/piskel/tree/fix-drawing-tests were mandatory, but looks like I was wrong :)

@david-szabo97  Would you mind extracting this commit to a separate PR so that we can merge it right away ?

**Comment by david-szabo97** [comment]
Seems to be stable now.
Moved the dependency upgrades to the new pull request.(https://github.com/juliandescottes/piskel/pull/536) Travis will fail here because it requires the latest PhantomJS

**Comment by juliandescottes** [comment]
Some additional feedback as I happened to test this integrated in piskel-website. Saving is no longer working with this PR. Since serializing now generates an arraybuffer, saving to piskelapp (GalleryStorageService) sends [object ArrayBuffer] to the server.

Is there any way we could split this in smaller PRs? At least one for the serialization format and one for the rest?

**Comment by david-szabo97** [comment]
I don't think we can split it into multiple PRs because the serialisation is coupled with the new format of piskel files.

I'm working on fixing the GalleryStorageService.

**Comment by juliandescottes** [comment]
Undo/redo no longer works on Firefox:
- draw anything
- undo (ctrl/cmd+Z)
- console logs an error "Image corrupt or truncated"
- redo does nothing

**Comment by juliandescottes** [comment]
Reviewed 6 of 36 files at r1, 5 of 18 files at r2.
Review status: 11 of 38 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/js/controller/FramesListController.js, line 14 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KQw_Fxta6AleF9zBkCx:-KQw_Fxta6AleF9zBkCy:b-rxh04k) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/controller/FramesListController.js#L14)):*
> ```JavaScript
>     this.piskelController = piskelController;
>     this.container = container;
>     this.domInitialized = false;
> ```

domInitialized and redrawFlag are both flags, we should synchronize their logic: true means there is something to do, false means there is nothing to do (or the other way around but both should follow the same logic)

---

*[src/js/controller/FramesListController.js, line 180 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KQw_mlKmnlOaiTgmgfF:-KQw_mlKmnlOaiTgmgfG:bxqqbza) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/controller/FramesListController.js#L180)):*
> ```JavaScript
> 
>     this.updateScrollerOverflows();
>     this.domInitialized = true;
> ```

flip this flag at the end of the render function (same place as the redraw flag). This method has no need to know about domInitialized

---

*[src/js/model/Frame.js, line 61 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRI-pG6zMyTApF9bIbR:-KRI-pG6zMyTApF9bIbS:b-v0ldur) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/model/Frame.js#L61)):*
> ```JavaScript
>       pixels = _emptyPixelGridCache[key] = new Uint32Array(width * height);
>       var transparentColorInt = pskl.utils.colorToInt(Constants.TRANSPARENT_COLOR);
>       if (!pixels.fill) { // PhantomJS ='(
> ```

If this polyfill is really only needed for Phantom, let's move it out of here. Either in utils/core.js, or in a new test file regrouping phantomJs polyfills ?

---

*[src/js/model/Frame.js, line 119 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRI29pUsxOPNwzU4aY9:-KRI29pUsxOPNwzU4aYA:b-4lbwk8) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/model/Frame.js#L119)):*
> ```JavaScript
>       var index = y * this.width + x;
>       var p = this.pixels[index];
>       if (typeof color === 'string') {
> ```

Isn't this redundant with the check (typeof color === 'number') in colorToInt?

---

*[src/js/model/Frame.js, line 142 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRI2po5fmLsbZj9aSxz:-KRI2po5fmLsbZj9aSy-:btn7umb) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/model/Frame.js#L142)):*
> ```JavaScript
>     var height = this.getHeight();
>     var length = width * height;
>     for (var i = 0; i < length ; ++i) {
> ```

nit: consistency, ++i -> i++

---

*[src/js/utils/PiskelFileUtils.js, line 32 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRIEL0NQ4EGsKtI3HUo:-KRIEL0NQ4EGsKtI3HUp:b1hmklp) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/utils/PiskelFileUtils.js#L32)):*
> ```JavaScript
>     decodePiskelFile : function (serializedPiskel, onSuccess, onError) {
>       pskl.utils.serialization.Deserializer.deserialize(serializedPiskel, function (piskel, extra) {
>         onSuccess(piskel, extra);
> ```

loadFromFile is also used in service/FileDropperService.js , which needs to be updated for this change (called when drag and dropping a Piskel file)

---

*[src/js/utils/serialization/Serializer.js, line 91 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRICOuO-c5iS70O176E:-KRICOuPwMC9xD6cBwBJ:b-n34jq9) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/utils/serialization/Serializer.js#L91)):*
> ```JavaScript
>       for (i = 0, layers = piskel.getLayers(); i < layers.length; i++) {
>         var renderer = new pskl.rendering.FramesheetRenderer(layers[i].getFrames());
>         dataUri = atob(renderer.renderAsCanvas().toDataURL().split(',')[1]);
> ```

As I mentioned, serialization / deserialization is no longer working on Firefox. It looks like the deserialized ending of the base64 png is different from the one that was serialized.
And from what I found, the PNG library used by Firefox seems more strict than the one used by other browsers and will reject PNGs with invalid endings (https://bugzilla.mozilla.org/show_bug.cgi?id=1003632)

I don't really have a lot of time to investigate this at the moment, sorry :( But testing quickly I found that using toDataURL('image/png') and getting rid of the atob/btoa transformation seemed to fix the issue. I'm still seeing a random "Image truncated" error log in Firefox, but not sure where this one comes from. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juliandescottes/piskel/530)*

**Comment by juliandescottes** [comment]
Sorry I'm taking a long time but this is really a huge change and I have very little bandwidth for Piskel at the moment. Again if you manage to split it, I could probably review isolated chunks faster.

A few nits so far, but mainly two bugs:
- drag and dropping a .piskel file on the editor no longer works (we should probably mutualize code here to avoid this kind of regressions in the future), should be an easy fix 
- serialization/deserialization issues on Firefox

Thanks again for your great work ; it will take time, but we'll get through the review :)

**Comment by juliandescottes** [comment]
Reviewed 6 of 36 files at r1, 6 of 18 files at r2, 1 of 1 files at r4.
Review status: 24 of 38 files reviewed at latest revision, 20 unresolved discussions.

---

*[src/js/controller/preview/PreviewController.js, line 6 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNDyz01lCPDRzV6cOs:-KRNDyz01lCPDRzV6cOt:b-vht0ex) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/controller/preview/PreviewController.js#L6)):*
> ```JavaScript
>   // Preview is a square of PREVIEW_SIZE x PREVIEW_SIZE
>   var PREVIEW_SIZE = 200;
>   var RENDER_MINIMUM_DELAY = 1000;
> ```

1000 ms feels a bit too long for the animated preview. Maybe settle on a lower value ? 

Ideally, we should enable throttling only when necessary, but that would be for another PR/issue.

For the frame list I think it's fine because you don't really look at it to see how your drawing evolves.

---

*[src/js/model/frame/AsyncCachedFrameProcessor.js, line 37 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNDG3cckdIsdWTSWyR:-KRNDG3cckdIsdWTSWyS:bb92mte) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/model/frame/AsyncCachedFrameProcessor.js#L37)):*
> ```JavaScript
>       var callbackFirstLvlCacheOnly = this.onProcessorComplete_.bind(this, deferred, cache, key1);
>       this.frameProcessor(frame, callbackFirstLvlCacheOnly);
>     } else {
> ```

get rid of the previous else if, both code paths are the same now

---

*[src/js/model/frame/AsyncCachedFrameProcessor.js, line 40 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNDRC0oFSX0ZaTlekb:-KRNDRC0oFSX0ZaTlekc:b-5r92zn) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/model/frame/AsyncCachedFrameProcessor.js#L40)):*
> ```JavaScript
>       var callback = this.onProcessorComplete_.bind(this, deferred, cache, key1);
>       this.frameProcessor(frame, callback);
>       cache[key1] = processedFrame;
> ```

Remove this line, processedFrame is not defined at this stage

---

*[src/js/model/frame/CachedFrameProcessor.js, line 73 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNCXhwJReQUO8Cw3Hg:-KRNCXhwJReQUO8Cw3Hh:b-gftbva) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/model/frame/CachedFrameProcessor.js#L73)):*
> ```JavaScript
>       processedFrame = this.frameProcessor(frame);
>       cache[cacheKey] = processedFrame;
>     } else {
> ```

Get rid of the else if above, as both code paths are now duplicated.

---

*[src/js/service/CurrentColorsService.js, line 74 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNGCE5NFZRLmlpZnz9:-KRNGCE5NFZRLmlpZnzA:b-75s435) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/service/CurrentColorsService.js#L74)):*
> ```JavaScript
>   };
> 
>   var rgbToHex = function (r, g, b) {
> ```

why not use pskl.utils.rgbToHex here? and potentially move your cache there?

---

*[src/js/service/CurrentColorsService.js, line 139 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNHts86Gwd-PMUkhTU:-KRNHts9-GaHECdjanUe:bjp6woi) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/service/CurrentColorsService.js#L139)):*
> ```JavaScript
> 
>       var hexColors = [];
>       for (var i in colors) {
> ```

I prefer we avoid using "for (var i in ...)". 
Either `Object.keys(colors).map(function (color) { return intToHex(color);})` or protect the loop with `colors.hasOwnProperty(i)` .

---

*[src/js/service/CurrentColorsService.js, line 170 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNIbVPjdZ6Mwb8n74W:-KRNIbVPjdZ6Mwb8n74X:bx74mk0) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/service/CurrentColorsService.js#L170)):*
> ```JavaScript
>   ns.CurrentColorsService.prototype.getFrameColors_ = function (frame, processorCallback) {
>     var frameColorsWorker = new pskl.worker.framecolors.FrameColors(frame,
>       function (event) {frameCache[frame.getHash()] = event.data.colors; processorCallback(event.data.colors);},
> ```

nit:  there are two instructions in this method, should stop being a oneliner.

---

*[src/js/service/storage/FileDownloadStorageService.js, line 16 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNP9etmxZFRAXPYCZa:-KRNP9etmxZFRAXPYCZb:b7e0t78) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/service/storage/FileDownloadStorageService.js#L16)):*
> ```JavaScript
> 
>     try {
>       pskl.utils.FileUtils.downloadAsFile(serialized, fileName);
> ```

Cast to new Blob([serialized]) here, see comment in FileUtils.js

---

*[src/js/tools/transform/TransformUtils.js, line 20 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNLW3saMp8nwpqIeL2:-KRNLW3saMp8nwpqIeL3:b-77in1y) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/tools/transform/TransformUtils.js#L20)):*
> ```JavaScript
>         frame.setPixel(x, y, color);
>       });
>       frame.version++;
> ```

Since you use setPixel now, you can normally get rid of this dirty frame.version++ :)

 I initially bypassed setPixel because it was a bit too slow here.

---

*[src/js/tools/transform/TransformUtils.js, line 107 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNLF51lgd36y_ROiZo:-KRNLF52h1snzuJ6futr:bxcfyx6) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/tools/transform/TransformUtils.js#L107)):*
> ```JavaScript
>         }
>       });
>       frame.version++;
> ```

Since you use setPixel now, you can normally get rid of this dirty frame.version++ :)

 I initially bypassed setPixel because it was a bit too slow here.

---

*[src/js/utils/core.js, line 126 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNKTyDfiJg2wCiLJPJ:-KRNKTyDfiJg2wCiLJPK:byzm1md) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/utils/core.js#L126)):*
> ```JavaScript
>   };
> 
>   var colorCache = {};
> ```

Not necessary, but I feel like we should move the color related utils to a dedicated file now.

---

*[src/js/utils/core.js, line 128 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNKhoaKX6StGLXKzaD:-KRNKhobr--wMW_c1rUP:b-x1qz7m) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/utils/core.js#L128)):*
> ```JavaScript
>   var colorCache = {};
>   var colorCacheReverse = {};
>   ns.colorToInt = function (color) {
> ```

Maybe add some unit tests for this method?

---

*[src/js/utils/FileUtils.js, line 39 \[r5\]](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNNypCVk2dSV6Y-3Mf:-KRNNypCVk2dSV6Y-3Mg:b-kn1a9f) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/utils/FileUtils.js#L39)):*
> ```JavaScript
>       } else {
>         var downloadLink = document.createElement('a');
>         content = window.URL.createObjectURL(new Blob([content]));
> ```

Should not cast new Blob([content]), content should already be a blob.
All callers still provide a blob here, except  the one you updated in  FileDownloadStorageService.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juliandescottes/piskel/530)*

**Comment by juliandescottes** [comment]
Some more comments, I hope to finish the code review in the next batch. I will need to spend some more time testing on various sprites, but looks good so far, no other bug found for now!

**Comment by juliandescottes** [comment]
Reviewed 6 of 36 files at r1, 6 of 18 files at r2, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 24 unresolved discussions.

---

*[src/js/service/storage/LocalStorageService.js, line 22 at r5](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRouWcn8Wx7Y-t3wF-b:-KRouWcn8Wx7Y-t3wF-c:be4v9c8) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/service/storage/LocalStorageService.js#L22)):*
> ```JavaScript
>     for (var i = 0, length = uint16.length; i < length; i++) {
>       serializedString += String.fromCharCode(uint16[i]);
>     }
> ```

Why is this being serialized differently from say, GalleryStorageService?

---

*[src/js/tools/drawing/ColorSwap.js, line 65 at r5](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRotvuDOqdPgRMeUD6L:-KRotvuDOqdPgRMeUD6M:b-7hq2sp) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/tools/drawing/ColorSwap.js#L65)):*
> ```JavaScript
>       }
>     });
>     frame.version++;
> ```

No  need for frame.version++ since you are using setPixel

---

*[src/js/utils/FrameUtils.js, line 37 at r5](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRoyMIUdqodb1gvJgOw:-KRoyMIUdqodb1gvJgOx:b-ppgvlz) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/utils/FrameUtils.js#L37)):*
> ```JavaScript
>         context = canvas.context;
>       } else {
>         context = canvas.context = canvas.getContext('2d');
> ```

Just curious, is caching the context really having an impact on performance here?

---

*[src/js/utils/serialization/Serializer.js, line 101 at r5](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRowB3-gOuvhfhdX_w1:-KRowB30SUlrTkD1rXbR:b-yy4tdi) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/utils/serialization/Serializer.js#L101)):*
> ```JavaScript
>       var arr8 = new Uint8Array(buffer);
>       var arr16 = new Uint16Array(buffer);
>       var sub;
> ```

var sub; not used, to remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juliandescottes/piskel/530)*

**Comment by juliandescottes** [comment]
Code review done! 
Really amazing work @david-szabo97 thanks a lot! 

Main items to check:
- Firefox issue with serialization
- reduce the throttling on the animated preview

+ a few nits and comments 

I will try to spend some time testing it with various sprites this week end. Really sorry about the delay for the review, but it is a big PR and I don't have a lot of time for Piskel at the moment.

**Comment by david-szabo97** [comment]
Review status: all files reviewed at latest revision, 24 unresolved discussions.

---

*[src/js/service/storage/LocalStorageService.js, line 22 at r5](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRouWcn8Wx7Y-t3wF-b:-KS8ODD86U01Sq1wOmbR:b-ss16jl) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/service/storage/LocalStorageService.js#L22)):*
<details><summary><i>Previously, juliandescottes (Julian Descottes) wrote…</i></summary>
> Why is this being serialized differently from say, GalleryStorageService?
</details>
We can only save strings to localStorage.
But I see what you mean. Maybe we should use this one for the GalleryStorageService too to save on space.

---

*[src/js/utils/FrameUtils.js, line 37 at r5](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRoyMIUdqodb1gvJgOw:-KS8P5G3ThS-gFkMUr-I:b70y1h0) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/utils/FrameUtils.js#L37)):*
<details><summary><i>Previously, juliandescottes (Julian Descottes) wrote…</i></summary>
> Just curious, is caching the context really having an impact on performance here?
</details>
I think it doesn't anymore but I will look into it.

---

*[src/js/utils/serialization/Serializer.js, line 91 at r5](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRICOuO-c5iS70O176E:-KS8PBQFJRPqT1Devmc4:bz6v06t) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/utils/serialization/Serializer.js#L91)):*
<details><summary><i>Previously, juliandescottes (Julian Descottes) wrote…</i></summary>
> As I mentioned, serialization / deserialization is no longer working on Firefox. It looks like the deserialized ending of the base64 png is different from the one that was serialized.
> And from what I found, the PNG library used by Firefox seems more strict than the one used by other browsers and will reject PNGs with invalid endings (https://bugzilla.mozilla.org/show_bug.cgi?id=1003632)
> 
> I don't really have a lot of time to investigate this at the moment, sorry :( But testing quickly I found that using toDataURL('image/png') and getting rid of the atob/btoa transformation seemed to fix the issue. I'm still seeing a random "Image truncated" error log in Firefox, but not sure where this one comes from. 
> 
</details>
I'll give it a try.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juliandescottes/piskel/530)*

**Comment by david-szabo97** [comment]
I fixed the image truncated errors in Firefox.
Unfortunately, it was a mistake made by me. (Forgot to add data URL length to byte calculation)
Though it's strange that it worked on chrome without any problems.

**Comment by juliandescottes** [comment]
@david-szabo97 Thank you for updating the PR ! Will take a look later today, hopefully we'll be good to go :)

I will probably do a release on piskelapp.com shortly after this gets merged. I'd be more than happy to do a shoutout when announcing the release on twitter, let me know if there's any url/account you'd like me to mention there!

> Though it's strange that it worked on chrome without any problems. 
From what I saw, Chrome and IE are using a more forgiving lib for decoding PNG images.

**Comment by juliandescottes** [comment]
Review status: 23 of 39 files reviewed at latest revision, 25 unresolved discussions.

---

*[src/js/controller/piskel/PiskelController.js, line 281 at r6](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KSYDrnIY2WFU1lPkh4F:-KSYDrnIY2WFU1lPkh4G:bwfbn22) ([raw file](https://github.com/juliandescottes/piskel/blob/7f0364289cdcc0cecadc60a968627e7769788193/src/js/controller/piskel/PiskelController.js#L281)):*
> ```JavaScript
>   };
> 
>   ns.PiskelController.prototype.serialize = function () {
> ```

BackupService uses  PiskelController::serialize to store the last edited sprite in local storage and ends up storing "[object ArrayBuffer]" 

---

*[src/js/tools/transform/TransformUtils.js, line 20 at r5](https://reviewable.io:443/reviews/juliandescottes/piskel/530#-KRNLW3saMp8nwpqIeL2:-KSYFhnNcO5cBFaznG-R:bsfv7da) ([raw file](https://github.com/juliandescottes/piskel/blob/86090ecb9abf0fe24a6a3bfd0aa6a7cd76951a84/src/js/tools/transform/TransformUtils.js#L20)):*
<details><summary><i>Previously, juliandescottes (Julian Descottes) wrote…</i></summary>
> Since you use setPixel now, you can normally get rid of this dirty frame.version++ :)
> 
>  I initially bypassed setPixel because it was a bit too slow here.
</details>
Comment still applies

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juliandescottes/piskel/530)*

**Comment by juliandescottes** [comment]
Getting another weird firefox only bug :(

Steps to reproduce:
- start with a 32x32 canvas
- draw a black 32x32 rectangle
- resize the canvas to 160x160, centered
- change color to red
- change tool to paint bucket
- click on any transparent pixel
- undo 
- click on any transparent pixel

-> The current colors show several duplicated "black" colors, some pixels might remain transparent.

image

**Comment by juliandescottes** [comment]
Looks like after the "undo" from my STRs, some of the black pixels are actually slightly transparent, and some of the transparent pixels are slightly opaque.

**Comment by juliandescottes** [comment]
Looks like the last issue I mentioned only occurs on the OSX version of Firefox.

I compared the output of the toDataUrl() calls performed during Serialization on Firefox windows and Firefox OSx, and they both create the same data-uri.

During Deserialization, after the image is drawn inside a canvas in createFramesFromSpritesheet(), getting the dataUri will show pixels with an opacity of 1/255 or 254/255. This means the image data gets modified either when loading that data-uri in the image tag or when drawing the image tag. 

We didn't have this issue before because the deserializer was only accepting 0 or 255 for the opacity (unless preserveOpacity was true). For now I would say we should use a similar approach. In the long run, maybe this means we should stop relying on PNG conversion to serialize/deserialize our sprites and instead use a format we completely control.

**Comment by juliandescottes** [comment]
@david-szabo97 I started adding performance measures in drawing tests. It's not super accurate but it measures:
- the time used to replay an event
- the time spent in rendering

The drawing tests we have right now all use super small sprites so they're not great for testing performance, so I also started creating a new test suite that you can run with http://localhost:9901/?debug&test-suite=DrawingTests.perf.js

I only have two tests in it and they're propably not great but already I can see great improvements comparing the figures I got on your branch vs master. One of the two tests is 10 time better (whatever that means considering what I measure here :) )!

**Comment by juliandescottes** [comment]
@david-szabo97 looks like the last thing to fix before merging is this firefox/osx issue. It would be totally fine with me to merge here, and address the issue in a followup (would be happy to take it, I don't know if you can even reproduce it on your hardware?)

Let me know how you want to proceed.

**Comment by david-szabo97** [comment]
@juliandescottes 
That would be great if you could take it. Unfortunately, I can't reproduce it (I don't own a mac) so I can't test it and address the issue.

**Comment by juliandescottes** [comment]
OK let's go ahead and merge then. 

Thanks again for the amazing work you've done here! The performance improvements coming from your PR are huge. You've managed to update the darkest corners of this codebase without any outside help... I am really astonished!

**Pull request merged**
