### PR TITLE
Copy between piskels

### PR DESCRIPTION
**Pull request by PSeitz**
#272

---
This change is [Reviewable](https://reviewable.io/reviews/juliandescottes/piskel/579)

### CODE REVIEW

**Comment by juliandescottes** [comment]
Thanks a lot for your PR and sorry for the delay! 
That seems to work well and I think it's a good start for the feature. 

I can see potentially 3 improvements that we could tackle in follow up issues:
- allow the user to move the pasted selection after hitting ctrl+v
- local storage space is limited, so maybe try to store the selected pixels in a more compact format
- show a notification when a clipboard info is available from another sprite (we would need to be able to identify which clipboard data comes from which "session" but that should be doable)

**Comment by Kuefet** [comment]
hello, so I am still stuck with one issue: I drew two different piskels, but can't copy and paste one from another. Are there any way to do that. note: I want to copy and paste only 1 frame. thanks a lot!

**Comment by juliandescottes** [comment]
[below I refer to piskel 1 and piskel 2 to represent the piskel from which you want ot copy, and the target piskel]

If you just want to copy one frame (and a single layer), normally you can:
- in piskel 1, select the area you want to copy with the selection tool
- hit CTRL+C (CMD+C on OSX) to put the selection in your clipboard
- in piskel 2, hit CTRL+V (or CMD+V on OSX)

This should paste the selected content from piskel 1 into your current frame of piskel 2. You might want to create an additional frame or layer in piskel 2 before pasting, to be able to easily move/adjust the pasted content.

copy-paste-between-piskel

**Comment by PSeitz** [comment]
I guess it's a litte weird to select something, by default it should probably copy the whole frame

**Comment by Kuefet** [comment]
woaw.. thank you!

**Pull request merged**
